name: local
variables:
  - name: base_url
    value: http://localhost:8080
  - name: user_email
    value: dhruv@splitplus.com
  - name: user_password
    value: password
  - name: access_token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiY2MwZDE1ZmItNTljNS00YzNhLTg3OTgtMDFiYmFmYjczMTJhIiwiZW1haWwiOiJkaHJ1dkBzcGxpdHBsdXMuY29tIiwiZXhwIjoxNzcwNjM4OTkxLCJuYmYiOjE3NzAwMzQxOTEsImlhdCI6MTc3MDAzNDE5MSwianRpIjoiYzBjZjZjNjYtNjE0Yy00M2MwLWFmZmUtMGI1ZDQwYTZlOThlIn0.0Ci6CliBXi6O_9V9YfGA0vGyD4xft7nd9JymoLI5x9k
  - name: refresh_token
    value: ""
  - name: user_id
    value: cc0d15fb-59c5-4c3a-8798-01bbafb7312a
  - name: group_id
    value: cf14da60-0df0-4c01-9410-b87f6bd62867
  - name: invite_user_id
    value: 2298497c-074d-4b22-b9c1-952dcf1b2a3c
  - name: expense_id
    value: 6c97cc40-fdcb-44c3-8bc1-6db47acd0d36
  - name: settlement_id
    value: ""
