// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balances.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGroupBalances = `-- name: GetGroupBalances :many
SELECT
    u.id AS user_id,
    u.email AS user_email,
    u.name AS user_name,
    u.avatar_url AS user_avatar_url,
    COALESCE(SUM(ep.amount), 0::DECIMAL) AS total_paid,
    COALESCE(SUM(es.amount_owned), 0::DECIMAL) AS total_owed
FROM group_members gm
JOIN users u ON gm.user_id = u.id
LEFT JOIN expenses e ON e.group_id = gm.group_id AND e.deleted_at IS NULL
LEFT JOIN expense_payments ep ON ep.expense_id = e.id AND ep.user_id = u.id AND ep.deleted_at IS NULL
LEFT JOIN expense_split es ON es.expense_id = e.id AND es.user_id = u.id AND es.deleted_at IS NULL
WHERE gm.group_id = $1 
    AND gm.status = 'active' 
    AND gm.deleted_at IS NULL
    AND u.deleted_at IS NULL
GROUP BY u.id, u.email, u.name, u.avatar_url
ORDER BY u.email
`

type GetGroupBalancesRow struct {
	UserID        pgtype.UUID `json:"user_id"`
	UserEmail     string      `json:"user_email"`
	UserName      pgtype.Text `json:"user_name"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
	TotalPaid     interface{} `json:"total_paid"`
	TotalOwed     interface{} `json:"total_owed"`
}

// Calculate balance for each user in a group
// Balance = total_paid - total_owed
// Positive balance means user is owed money, negative means user owes money
func (q *Queries) GetGroupBalances(ctx context.Context, groupID pgtype.UUID) ([]GetGroupBalancesRow, error) {
	rows, err := q.db.Query(ctx, getGroupBalances, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupBalancesRow{}
	for rows.Next() {
		var i GetGroupBalancesRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.UserAvatarUrl,
			&i.TotalPaid,
			&i.TotalOwed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverallUserBalance = `-- name: GetOverallUserBalance :many
SELECT
    g.id AS group_id,
    g.name AS group_name,
    g.currency_code AS currency_code,
    COALESCE(SUM(ep.amount), 0::DECIMAL) AS total_paid,
    COALESCE(SUM(es.amount_owned), 0::DECIMAL) AS total_owed
FROM group_members gm
JOIN groups g ON gm.group_id = g.id
LEFT JOIN expenses e ON e.group_id = gm.group_id AND e.deleted_at IS NULL
LEFT JOIN expense_payments ep ON ep.expense_id = e.id AND ep.user_id = gm.user_id AND ep.deleted_at IS NULL
LEFT JOIN expense_split es ON es.expense_id = e.id AND es.user_id = gm.user_id AND es.deleted_at IS NULL
WHERE gm.user_id = $1
    AND gm.status = 'active'
    AND gm.deleted_at IS NULL
    AND g.deleted_at IS NULL
GROUP BY g.id, g.name, g.currency_code
ORDER BY g.name
`

type GetOverallUserBalanceRow struct {
	GroupID      pgtype.UUID `json:"group_id"`
	GroupName    string      `json:"group_name"`
	CurrencyCode string      `json:"currency_code"`
	TotalPaid    interface{} `json:"total_paid"`
	TotalOwed    interface{} `json:"total_owed"`
}

// Get user's balance across all groups
func (q *Queries) GetOverallUserBalance(ctx context.Context, userID pgtype.UUID) ([]GetOverallUserBalanceRow, error) {
	rows, err := q.db.Query(ctx, getOverallUserBalance, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverallUserBalanceRow{}
	for rows.Next() {
		var i GetOverallUserBalanceRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.CurrencyCode,
			&i.TotalPaid,
			&i.TotalOwed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBalanceInGroup = `-- name: GetUserBalanceInGroup :one
SELECT
    u.id AS user_id,
    u.email AS user_email,
    u.name AS user_name,
    u.avatar_url AS user_avatar_url,
    COALESCE(SUM(ep.amount), 0::DECIMAL) AS total_paid,
    COALESCE(SUM(es.amount_owned), 0::DECIMAL) AS total_owed,
    COALESCE(SUM(ep.amount), 0::DECIMAL) - COALESCE(SUM(es.amount_owned), 0::DECIMAL) AS balance
FROM group_members gm
JOIN users u ON gm.user_id = u.id
LEFT JOIN expenses e ON e.group_id = gm.group_id AND e.deleted_at IS NULL
LEFT JOIN expense_payments ep ON ep.expense_id = e.id AND ep.user_id = u.id AND ep.deleted_at IS NULL
LEFT JOIN expense_split es ON es.expense_id = e.id AND es.user_id = u.id AND es.deleted_at IS NULL
WHERE gm.group_id = $1 
    AND gm.user_id = $2
    AND gm.status = 'active' 
    AND gm.deleted_at IS NULL
    AND u.deleted_at IS NULL
GROUP BY u.id, u.email, u.name, u.avatar_url
`

type GetUserBalanceInGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type GetUserBalanceInGroupRow struct {
	UserID        pgtype.UUID `json:"user_id"`
	UserEmail     string      `json:"user_email"`
	UserName      pgtype.Text `json:"user_name"`
	UserAvatarUrl pgtype.Text `json:"user_avatar_url"`
	TotalPaid     interface{} `json:"total_paid"`
	TotalOwed     interface{} `json:"total_owed"`
	Balance       int32       `json:"balance"`
}

// Get balance for a specific user in a group
func (q *Queries) GetUserBalanceInGroup(ctx context.Context, arg GetUserBalanceInGroupParams) (GetUserBalanceInGroupRow, error) {
	row := q.db.QueryRow(ctx, getUserBalanceInGroup, arg.GroupID, arg.UserID)
	var i GetUserBalanceInGroupRow
	err := row.Scan(
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.UserAvatarUrl,
		&i.TotalPaid,
		&i.TotalOwed,
		&i.Balance,
	)
	return i, err
}
