// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupCategory = `-- name: CreateGroupCategory :one
INSERT INTO expense_categories (
    group_id,
    slug,
    name,
    icon,
    color,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $6
) RETURNING id, group_id, slug, name, icon, color, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateGroupCategoryParams struct {
	GroupID   pgtype.UUID `json:"group_id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	Icon      pgtype.Text `json:"icon"`
	Color     pgtype.Text `json:"color"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateGroupCategory(ctx context.Context, arg CreateGroupCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createGroupCategory,
		arg.GroupID,
		arg.Slug,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.CreatedBy,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const deleteGroupCategory = `-- name: DeleteGroupCategory :exec
UPDATE expense_categories
SET 
    deleted_at = CURRENT_TIMESTAMP,
    updated_by = $2
WHERE id = $1 
  AND deleted_at IS NULL
`

type DeleteGroupCategoryParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) DeleteGroupCategory(ctx context.Context, arg DeleteGroupCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteGroupCategory, arg.ID, arg.UpdatedBy)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, group_id, slug, name, icon, color, created_at, created_by, updated_at, updated_by, deleted_at FROM expense_categories
WHERE id = $1 
  AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, group_id, slug, name, icon, color, created_at, created_by, updated_at, updated_by, deleted_at FROM expense_categories
WHERE group_id = $1 
  AND slug = $2 
  AND deleted_at IS NULL
`

type GetCategoryBySlugParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.GroupID, arg.Slug)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listCategoriesForGroup = `-- name: ListCategoriesForGroup :many
SELECT id, group_id, slug, name, icon, color, created_at, created_by, updated_at, updated_by, deleted_at FROM expense_categories
WHERE group_id = $1 
  AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListCategoriesForGroup(ctx context.Context, groupID pgtype.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listCategoriesForGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Slug,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupCategory = `-- name: UpdateGroupCategory :one
UPDATE expense_categories
SET 
    slug = $2,
    name = $3,
    icon = $4,
    color = $5,
    updated_by = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 
  AND deleted_at IS NULL
RETURNING id, group_id, slug, name, icon, color, created_at, created_by, updated_at, updated_by, deleted_at
`

type UpdateGroupCategoryParams struct {
	ID        pgtype.UUID `json:"id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	Icon      pgtype.Text `json:"icon"`
	Color     pgtype.Text `json:"color"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateGroupCategory(ctx context.Context, arg UpdateGroupCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateGroupCategory,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.UpdatedBy,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
