// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpenseComments = `-- name: CountExpenseComments :one
SELECT COUNT(*) FROM expense_comments
WHERE expense_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountExpenseComments(ctx context.Context, expenseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseComments, expenseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpenseComment = `-- name: CreateExpenseComment :one
INSERT INTO expense_comments (
    expense_id,
    user_id,
    comment
) VALUES (
    $1, $2, $3
) RETURNING id, expense_id, user_id, comment, created_at, updated_at, deleted_at
`

type CreateExpenseCommentParams struct {
	ExpenseID pgtype.UUID `json:"expense_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Comment   string      `json:"comment"`
}

func (q *Queries) CreateExpenseComment(ctx context.Context, arg CreateExpenseCommentParams) (ExpenseComment, error) {
	row := q.db.QueryRow(ctx, createExpenseComment, arg.ExpenseID, arg.UserID, arg.Comment)
	var i ExpenseComment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpenseComment = `-- name: DeleteExpenseComment :exec
UPDATE expense_comments
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteExpenseComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseComment, id)
	return err
}

const getExpenseCommentByID = `-- name: GetExpenseCommentByID :one
SELECT 
    c.id, c.expense_id, c.user_id, c.comment, c.created_at, c.updated_at, c.deleted_at,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM expense_comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetExpenseCommentByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	ExpenseID     pgtype.UUID        `json:"expense_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Comment       string             `json:"comment"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) GetExpenseCommentByID(ctx context.Context, id pgtype.UUID) (GetExpenseCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseCommentByID, id)
	var i GetExpenseCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listExpenseComments = `-- name: ListExpenseComments :many
SELECT 
    c.id, c.expense_id, c.user_id, c.comment, c.created_at, c.updated_at, c.deleted_at,
    u.name as user_name,
    u.email as user_email,
    u.avatar_url as user_avatar_url
FROM expense_comments c
JOIN users u ON c.user_id = u.id
WHERE c.expense_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
`

type ListExpenseCommentsRow struct {
	ID            pgtype.UUID        `json:"id"`
	ExpenseID     pgtype.UUID        `json:"expense_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Comment       string             `json:"comment"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserName      pgtype.Text        `json:"user_name"`
	UserEmail     string             `json:"user_email"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListExpenseComments(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseCommentsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseComments, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpenseCommentsRow{}
	for rows.Next() {
		var i ListExpenseCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseComment = `-- name: UpdateExpenseComment :one
UPDATE expense_comments
SET 
    comment = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, expense_id, user_id, comment, created_at, updated_at, deleted_at
`

type UpdateExpenseCommentParams struct {
	ID      pgtype.UUID `json:"id"`
	Comment string      `json:"comment"`
}

func (q *Queries) UpdateExpenseComment(ctx context.Context, arg UpdateExpenseCommentParams) (ExpenseComment, error) {
	row := q.db.QueryRow(ctx, updateExpenseComment, arg.ID, arg.Comment)
	var i ExpenseComment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
