// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (user_id, friend_user_id, status)
VALUES ($1, $2, $3) RETURNING id, user_id, friend_user_id, status, created_at, updated_at, deleted_at
`

type CreateFriendshipParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	FriendUserID pgtype.UUID `json:"friend_user_id"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserID, arg.FriendUserID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
UPDATE friendships
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteFriendship(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendship, id)
	return err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, user_id, friend_user_id, status, created_at, updated_at, deleted_at FROM friendships
WHERE user_id = $1 AND friend_user_id = $2 AND deleted_at IS NULL
`

type GetFriendshipParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	FriendUserID pgtype.UUID `json:"friend_user_id"`
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserID, arg.FriendUserID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, user_id, friend_user_id, status, created_at, updated_at, deleted_at FROM friendships
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFriends = `-- name: ListFriends :many
SELECT
    f.id,
    f.user_id,
    f.friend_user_id,
    f.status,
    f.created_at,
    f.updated_at,
    u.id AS friend_id,
    u.email AS friend_email,
    u.name AS friend_name,
    u.avatar_url AS friend_avatar_url
FROM friendships f
JOIN users u
  ON (CASE WHEN f.user_id = $1 THEN f.friend_user_id ELSE f.user_id END) = u.id
WHERE (f.user_id = $1 OR f.friend_user_id = $1)
  AND f.status = 'accepted'
  AND f.deleted_at IS NULL
ORDER BY u.email
`

type ListFriendsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	FriendUserID    pgtype.UUID        `json:"friend_user_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FriendID        pgtype.UUID        `json:"friend_id"`
	FriendEmail     string             `json:"friend_email"`
	FriendName      pgtype.Text        `json:"friend_name"`
	FriendAvatarUrl pgtype.Text        `json:"friend_avatar_url"`
}

func (q *Queries) ListFriends(ctx context.Context, userID pgtype.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FriendID,
			&i.FriendEmail,
			&i.FriendName,
			&i.FriendAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT id, user_id, friend_user_id, status, created_at, updated_at, deleted_at FROM friendships
WHERE friend_user_id = $1
  AND status = 'pending'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, friendUserID pgtype.UUID) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, friendUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT id, user_id, friend_user_id, status, created_at, updated_at, deleted_at FROM friendships
WHERE user_id = $1
  AND status = 'pending'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, userID pgtype.UUID) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FriendUserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendships
SET status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, user_id, friend_user_id, status, created_at, updated_at, deleted_at
`

type UpdateFriendshipStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, updateFriendshipStatus, arg.ID, arg.Status)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
