// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group-members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, user_id, role, status, invited_by, invited_at, joined_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, group_id, user_id, role, status, invited_by, invited_at, joined_at, created_at, updated_at, deleted_at
`

type CreateGroupMemberParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.InvitedBy,
		arg.InvitedAt,
		arg.JoinedAt,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, role, status, invited_by, invited_at, joined_at, created_at, updated_at, deleted_at FROM group_members
WHERE group_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupsByUserID = `-- name: GetGroupsByUserID :many
SELECT
    g.id,
    g.name,
    g.description,
    g.currency_code,
    g.created_at,
    gm.id as membership_id,
    gm.role as member_role,
    gm.status as member_status,
    gm.joined_at as member_joined_at
FROM group_members AS gm
INNER JOIN groups AS g ON gm.group_id = g.id
WHERE gm.user_id = $1 AND gm.deleted_at IS NULL AND g.deleted_at IS NULL
ORDER BY g.created_at DESC
`

type GetGroupsByUserIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	CurrencyCode   string             `json:"currency_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MembershipID   pgtype.UUID        `json:"membership_id"`
	MemberRole     string             `json:"member_role"`
	MemberStatus   string             `json:"member_status"`
	MemberJoinedAt pgtype.Timestamptz `json:"member_joined_at"`
}

func (q *Queries) GetGroupsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetGroupsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGroupsByUserIDRow{}
	for rows.Next() {
		var i GetGroupsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CurrencyCode,
			&i.CreatedAt,
			&i.MembershipID,
			&i.MemberRole,
			&i.MemberStatus,
			&i.MemberJoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT
    gm.id,
    gm.group_id,
    gm.user_id,
    gm.role,
    gm.status,
    gm.invited_by,
    gm.invited_at,
    gm.joined_at,
    gm.created_at,
    gm.updated_at,
    u.email AS user_email,
    u.name AS user_name,
    u.avatar_url AS user_avatar_url
FROM group_members gm
JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1
    AND gm.deleted_at IS NULL
    AND gm.status IN ('active', 'pending')
ORDER BY gm.created_at ASC
`

type ListGroupMembersRow struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	InvitedBy     pgtype.UUID        `json:"invited_by"`
	InvitedAt     pgtype.Timestamptz `json:"invited_at"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UserEmail     string             `json:"user_email"`
	UserName      pgtype.Text        `json:"user_name"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupMemberStatus = `-- name: UpdateGroupMemberStatus :one
UPDATE group_members
SET status = $3, joined_at = $4, updated_at = CURRENT_TIMESTAMP
WHERE group_id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, group_id, user_id, role, status, invited_by, invited_at, joined_at, created_at, updated_at, deleted_at
`

type UpdateGroupMemberStatusParams struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Status   string             `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberStatus,
		arg.GroupID,
		arg.UserID,
		arg.Status,
		arg.JoinedAt,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
