// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO group_invitations (group_id, email, token, role, status, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, group_id, email, token, role, status, invited_by, expires_at, created_at, updated_at
`

type CreateInvitationParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (GroupInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.GroupID,
		arg.Email,
		arg.Token,
		arg.Role,
		arg.Status,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, group_id, email, token, role, status, invited_by, expires_at, created_at, updated_at FROM group_invitations
WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id pgtype.UUID) (GroupInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT gi.id, gi.group_id, gi.email, gi.token, gi.role, gi.status, gi.invited_by, gi.expires_at, gi.created_at, gi.updated_at, g.name as group_name 
FROM group_invitations gi
JOIN groups g ON gi.group_id = g.id
WHERE gi.token = $1 AND gi.status = 'pending' AND gi.expires_at > NOW()
`

type GetInvitationByTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	GroupName string             `json:"group_name"`
}

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i GetInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupName,
	)
	return i, err
}

const getPendingInvitationsByEmail = `-- name: GetPendingInvitationsByEmail :many
SELECT gi.id, gi.group_id, gi.email, gi.token, gi.role, gi.status, gi.invited_by, gi.expires_at, gi.created_at, gi.updated_at, g.name as group_name, u.name as inviter_name
FROM group_invitations gi
JOIN groups g ON gi.group_id = g.id
JOIN users u ON gi.invited_by = u.id
WHERE gi.email = $1 AND gi.status = 'pending' AND gi.expires_at > NOW()
`

type GetPendingInvitationsByEmailRow struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	Email       string             `json:"email"`
	Token       string             `json:"token"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GroupName   string             `json:"group_name"`
	InviterName pgtype.Text        `json:"inviter_name"`
}

func (q *Queries) GetPendingInvitationsByEmail(ctx context.Context, email string) ([]GetPendingInvitationsByEmailRow, error) {
	rows, err := q.db.Query(ctx, getPendingInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingInvitationsByEmailRow{}
	for rows.Next() {
		var i GetPendingInvitationsByEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsByGroup = `-- name: ListInvitationsByGroup :many
SELECT id, group_id, email, token, role, status, invited_by, expires_at, created_at, updated_at FROM group_invitations
WHERE group_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByGroup(ctx context.Context, groupID pgtype.UUID) ([]GroupInvitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupInvitation{}
	for rows.Next() {
		var i GroupInvitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Email,
			&i.Token,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE group_invitations
SET status = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, group_id, email, token, role, status, invited_by, expires_at, created_at, updated_at
`

type UpdateInvitationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (GroupInvitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i GroupInvitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Email,
		&i.Token,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
