// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, currency_code, created_by, updated_by)
VALUES ($1, $2, $3, $4, $4) RETURNING id, name, description, currency_code, default_split_method, settings, created_at, created_by, updated_at, updated_by, deleted_at
`

type CreateGroupParams struct {
	Name         string      `json:"name"`
	Description  pgtype.Text `json:"description"`
	CurrencyCode string      `json:"currency_code"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.CurrencyCode,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrencyCode,
		&i.DefaultSplitMethod,
		&i.Settings,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, currency_code, default_split_method, settings, created_at, created_by, updated_at, updated_by, deleted_at FROM groups
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CurrencyCode,
		&i.DefaultSplitMethod,
		&i.Settings,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
