// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_activities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupActivity = `-- name: CreateGroupActivity :one
INSERT INTO group_activities (
    group_id,
    user_id,
    action,
    entity_type,
    entity_id,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, group_id, user_id, action, entity_type, entity_id, metadata, created_at
`

type CreateGroupActivityParams struct {
	GroupID    pgtype.UUID `json:"group_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateGroupActivity(ctx context.Context, arg CreateGroupActivityParams) (GroupActivity, error) {
	row := q.db.QueryRow(ctx, createGroupActivity,
		arg.GroupID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i GroupActivity
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseHistory = `-- name: GetExpenseHistory :many
SELECT 
    ga.id,
    ga.group_id,
    ga.user_id,
    ga.action,
    ga.entity_type,
    ga.entity_id,
    ga.metadata,
    ga.created_at,
    u.email as user_email,
    u.name as user_name,
    u.avatar_url as user_avatar_url
FROM group_activities ga
JOIN users u ON ga.user_id = u.id
WHERE ga.entity_type = 'expense' 
  AND ga.entity_id = $1
ORDER BY ga.created_at DESC
`

type GetExpenseHistoryRow struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Action        string             `json:"action"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserEmail     string             `json:"user_email"`
	UserName      pgtype.Text        `json:"user_name"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) GetExpenseHistory(ctx context.Context, entityID pgtype.UUID) ([]GetExpenseHistoryRow, error) {
	rows, err := q.db.Query(ctx, getExpenseHistory, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpenseHistoryRow{}
	for rows.Next() {
		var i GetExpenseHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupActivities = `-- name: ListGroupActivities :many
SELECT 
    ga.id,
    ga.group_id,
    ga.user_id,
    ga.action,
    ga.entity_type,
    ga.entity_id,
    ga.metadata,
    ga.created_at,
    u.email as user_email,
    u.name as user_name,
    u.avatar_url as user_avatar_url
FROM group_activities ga
JOIN users u ON ga.user_id = u.id
WHERE ga.group_id = $1
ORDER BY ga.created_at DESC
LIMIT $2 OFFSET $3
`

type ListGroupActivitiesParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListGroupActivitiesRow struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Action        string             `json:"action"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserEmail     string             `json:"user_email"`
	UserName      pgtype.Text        `json:"user_name"`
	UserAvatarUrl pgtype.Text        `json:"user_avatar_url"`
}

func (q *Queries) ListGroupActivities(ctx context.Context, arg ListGroupActivitiesParams) ([]ListGroupActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listGroupActivities, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupActivitiesRow{}
	for rows.Next() {
		var i ListGroupActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserEmail,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
