// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Title        string             `json:"title"`
	Notes        pgtype.Text        `json:"notes"`
	Amount       pgtype.Numeric     `json:"amount"`
	CurrencyCode string             `json:"currency_code"`
	Date         pgtype.Date        `json:"date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	Type         string             `json:"type"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	Tags         []string           `json:"tags"`
}

type ExpenseCategory struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Icon      pgtype.Text        `json:"icon"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ExpenseComment struct {
	ID        pgtype.UUID        `json:"id"`
	ExpenseID pgtype.UUID        `json:"expense_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Comment   string             `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ExpensePayment struct {
	ID            pgtype.UUID        `json:"id"`
	ExpenseID     pgtype.UUID        `json:"expense_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	PendingUserID pgtype.UUID        `json:"pending_user_id"`
}

type ExpenseSplit struct {
	ID            pgtype.UUID        `json:"id"`
	ExpenseID     pgtype.UUID        `json:"expense_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	AmountOwned   pgtype.Numeric     `json:"amount_owned"`
	SplitType     string             `json:"split_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	PendingUserID pgtype.UUID        `json:"pending_user_id"`
}

type Friendship struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FriendUserID pgtype.UUID        `json:"friend_user_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Group struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	CurrencyCode       string             `json:"currency_code"`
	DefaultSplitMethod string             `json:"default_split_method"`
	Settings           []byte             `json:"settings"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type GroupActivity struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GroupInvitation struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	InvitedAt pgtype.Timestamptz `json:"invited_at"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type PendingUser struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      pgtype.Text        `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RecurringExpense struct {
	ID                 pgtype.UUID        `json:"id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	Title              string             `json:"title"`
	Notes              pgtype.Text        `json:"notes"`
	Amount             pgtype.Numeric     `json:"amount"`
	CurrencyCode       string             `json:"currency_code"`
	RepeatInterval     string             `json:"repeat_interval"`
	DayOfMonth         pgtype.Int4        `json:"day_of_month"`
	DayOfWeek          pgtype.Int4        `json:"day_of_week"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	NextOccurrenceDate pgtype.Date        `json:"next_occurrence_date"`
	IsActive           pgtype.Bool        `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type RecurringExpensePayment struct {
	ID                 pgtype.UUID        `json:"id"`
	RecurringExpenseID pgtype.UUID        `json:"recurring_expense_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	Amount             pgtype.Numeric     `json:"amount"`
	PaymentMethod      pgtype.Text        `json:"payment_method"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type RecurringExpenseSplit struct {
	ID                 pgtype.UUID        `json:"id"`
	RecurringExpenseID pgtype.UUID        `json:"recurring_expense_id"`
	UserID             pgtype.UUID        `json:"user_id"`
	AmountOwned        pgtype.Numeric     `json:"amount_owned"`
	SplitType          string             `json:"split_type"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Settlement struct {
	ID                   pgtype.UUID        `json:"id"`
	GroupID              pgtype.UUID        `json:"group_id"`
	PayerID              pgtype.UUID        `json:"payer_id"`
	PayeeID              pgtype.UUID        `json:"payee_id"`
	Amount               pgtype.Numeric     `json:"amount"`
	CurrencyCode         string             `json:"currency_code"`
	Status               string             `json:"status"`
	PaymentMethod        pgtype.Text        `json:"payment_method"`
	TransactionReference pgtype.Text        `json:"transaction_reference"`
	PaidAt               pgtype.Timestamptz `json:"paid_at"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	Type                 string             `json:"type"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	PasswordHash    string             `json:"password_hash"`
	Name            pgtype.Text        `json:"name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Language        string             `json:"language"`
	Timezone        string             `json:"timezone"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
