// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingUser = `-- name: CreatePendingUser :one
INSERT INTO pending_users (email, name)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE 
SET name = COALESCE(EXCLUDED.name, pending_users.name), 
    updated_at = NOW()
RETURNING id, email, name, created_at, updated_at
`

type CreatePendingUserParams struct {
	Email string      `json:"email"`
	Name  pgtype.Text `json:"name"`
}

func (q *Queries) CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (PendingUser, error) {
	row := q.db.QueryRow(ctx, createPendingUser, arg.Email, arg.Name)
	var i PendingUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePendingUserByID = `-- name: DeletePendingUserByID :exec
DELETE FROM pending_users WHERE id = $1
`

func (q *Queries) DeletePendingUserByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingUserByID, id)
	return err
}

const getPendingUserByEmail = `-- name: GetPendingUserByEmail :one
SELECT id, email, name, created_at, updated_at FROM pending_users WHERE email = $1
`

func (q *Queries) GetPendingUserByEmail(ctx context.Context, email string) (PendingUser, error) {
	row := q.db.QueryRow(ctx, getPendingUserByEmail, email)
	var i PendingUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingUserByID = `-- name: GetPendingUserByID :one
SELECT id, email, name, created_at, updated_at FROM pending_users WHERE id = $1
`

func (q *Queries) GetPendingUserByID(ctx context.Context, id pgtype.UUID) (PendingUser, error) {
	row := q.db.QueryRow(ctx, getPendingUserByID, id)
	var i PendingUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePendingPaymentUserID = `-- name: UpdatePendingPaymentUserID :exec
UPDATE expense_payments
SET user_id = $1, pending_user_id = NULL
WHERE pending_user_id = $2
`

type UpdatePendingPaymentUserIDParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PendingUserID pgtype.UUID `json:"pending_user_id"`
}

func (q *Queries) UpdatePendingPaymentUserID(ctx context.Context, arg UpdatePendingPaymentUserIDParams) error {
	_, err := q.db.Exec(ctx, updatePendingPaymentUserID, arg.UserID, arg.PendingUserID)
	return err
}

const updatePendingSettlementPayeeUserID = `-- name: UpdatePendingSettlementPayeeUserID :exec
UPDATE settlements
SET payee_id = $1,
    payee_pending_user_id = NULL
WHERE payee_pending_user_id = $2
`

type UpdatePendingSettlementPayeeUserIDParams struct {
	PayeeID            pgtype.UUID `json:"payee_id"`
	PayeePendingUserID pgtype.UUID `json:"payee_pending_user_id"`
}

func (q *Queries) UpdatePendingSettlementPayeeUserID(ctx context.Context, arg UpdatePendingSettlementPayeeUserIDParams) error {
	_, err := q.db.Exec(ctx, updatePendingSettlementPayeeUserID, arg.PayeeID, arg.PayeePendingUserID)
	return err
}

const updatePendingSettlementPayerUserID = `-- name: UpdatePendingSettlementPayerUserID :exec
UPDATE settlements
SET payer_id = $1,
    payer_pending_user_id = NULL
WHERE payer_pending_user_id = $2
`

type UpdatePendingSettlementPayerUserIDParams struct {
	PayerID            pgtype.UUID `json:"payer_id"`
	PayerPendingUserID pgtype.UUID `json:"payer_pending_user_id"`
}

func (q *Queries) UpdatePendingSettlementPayerUserID(ctx context.Context, arg UpdatePendingSettlementPayerUserIDParams) error {
	_, err := q.db.Exec(ctx, updatePendingSettlementPayerUserID, arg.PayerID, arg.PayerPendingUserID)
	return err
}

const updatePendingSplitUserID = `-- name: UpdatePendingSplitUserID :exec
UPDATE expense_split
SET user_id = $1, pending_user_id = NULL
WHERE pending_user_id = $2
`

type UpdatePendingSplitUserIDParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	PendingUserID pgtype.UUID `json:"pending_user_id"`
}

func (q *Queries) UpdatePendingSplitUserID(ctx context.Context, arg UpdatePendingSplitUserIDParams) error {
	_, err := q.db.Exec(ctx, updatePendingSplitUserID, arg.UserID, arg.PendingUserID)
	return err
}
