// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BlacklistToken(ctx context.Context, arg BlacklistTokenParams) error
	CountExpenseComments(ctx context.Context, expenseID pgtype.UUID) (int64, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseComment(ctx context.Context, arg CreateExpenseCommentParams) (ExpenseComment, error)
	CreateExpensePayment(ctx context.Context, arg CreateExpensePaymentParams) (ExpensePayment, error)
	CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupActivity(ctx context.Context, arg CreateGroupActivityParams) (GroupActivity, error)
	CreateGroupCategory(ctx context.Context, arg CreateGroupCategoryParams) (ExpenseCategory, error)
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (GroupInvitation, error)
	CreatePendingUser(ctx context.Context, arg CreatePendingUserParams) (PendingUser, error)
	CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error)
	CreateRecurringExpensePayment(ctx context.Context, arg CreateRecurringExpensePaymentParams) (RecurringExpensePayment, error)
	CreateRecurringExpenseSplit(ctx context.Context, arg CreateRecurringExpenseSplitParams) (RecurringExpenseSplit, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	DeleteExpense(ctx context.Context, id pgtype.UUID) error
	DeleteExpenseComment(ctx context.Context, id pgtype.UUID) error
	DeleteExpensePayments(ctx context.Context, expenseID pgtype.UUID) error
	DeleteExpenseSplits(ctx context.Context, expenseID pgtype.UUID) error
	DeleteExpiredBlacklistedTokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFriendship(ctx context.Context, id pgtype.UUID) error
	DeleteGroupCategory(ctx context.Context, arg DeleteGroupCategoryParams) error
	DeleteRecurringExpense(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, refreshTokenHash string) error
	DeleteSettlement(ctx context.Context, id pgtype.UUID) error
	GetActiveSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (ExpenseCategory, error)
	GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (ExpenseCategory, error)
	GetExpenseByID(ctx context.Context, id pgtype.UUID) (Expense, error)
	GetExpenseCommentByID(ctx context.Context, id pgtype.UUID) (GetExpenseCommentByIDRow, error)
	GetExpenseHistory(ctx context.Context, entityID pgtype.UUID) ([]GetExpenseHistoryRow, error)
	GetFriendship(ctx context.Context, arg GetFriendshipParams) (Friendship, error)
	GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error)
	// Calculate balance for each user in a group
	// Balance = total_paid - total_owed
	// Positive balance means user is owed money, negative means user owes money
	GetGroupBalances(ctx context.Context, groupID pgtype.UUID) ([]GetGroupBalancesRow, error)
	// Calculate balance for each user or pending user in a group
	// Balance = total_paid - total_owed
	// Positive balance means entity is owed money, negative means entity owes money
	GetGroupBalancesWithPending(ctx context.Context, groupID pgtype.UUID) ([]GetGroupBalancesWithPendingRow, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetGroupsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetGroupsByUserIDRow, error)
	GetInvitationByID(ctx context.Context, id pgtype.UUID) (GroupInvitation, error)
	GetInvitationByToken(ctx context.Context, token string) (GetInvitationByTokenRow, error)
	// Get user's balance across all groups
	GetOverallUserBalance(ctx context.Context, userID pgtype.UUID) ([]GetOverallUserBalanceRow, error)
	GetPendingInvitationsByEmail(ctx context.Context, email string) ([]GetPendingInvitationsByEmailRow, error)
	GetPendingUserByEmail(ctx context.Context, email string) (PendingUser, error)
	GetPendingUserByID(ctx context.Context, id pgtype.UUID) (PendingUser, error)
	GetRecurringExpenseByID(ctx context.Context, id pgtype.UUID) (RecurringExpense, error)
	GetRecurringExpensesDue(ctx context.Context) ([]RecurringExpense, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSettlementByID(ctx context.Context, id pgtype.UUID) (Settlement, error)
	// Get balance for a specific user in a group
	GetUserBalanceInGroup(ctx context.Context, arg GetUserBalanceInGroupParams) (GetUserBalanceInGroupRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	IsTokenBlacklisted(ctx context.Context, tokenJti string) (bool, error)
	ListCategoriesForGroup(ctx context.Context, groupID pgtype.UUID) ([]ExpenseCategory, error)
	ListExpenseComments(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseCommentsRow, error)
	ListExpensePayments(ctx context.Context, expenseID pgtype.UUID) ([]ListExpensePaymentsRow, error)
	ListExpenseSplits(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseSplitsRow, error)
	ListExpensesByGroup(ctx context.Context, groupID pgtype.UUID) ([]Expense, error)
	ListFriendExpenses(ctx context.Context, arg ListFriendExpensesParams) ([]Expense, error)
	ListFriendSettlements(ctx context.Context, arg ListFriendSettlementsParams) ([]ListFriendSettlementsRow, error)
	ListFriends(ctx context.Context, userID pgtype.UUID) ([]ListFriendsRow, error)
	ListGroupActivities(ctx context.Context, arg ListGroupActivitiesParams) ([]ListGroupActivitiesRow, error)
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error)
	ListIncomingFriendRequests(ctx context.Context, friendUserID pgtype.UUID) ([]Friendship, error)
	ListInvitationsByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListInvitationsByGroupRow, error)
	ListOutgoingFriendRequests(ctx context.Context, userID pgtype.UUID) ([]Friendship, error)
	ListRecurringExpensePayments(ctx context.Context, recurringExpenseID pgtype.UUID) ([]ListRecurringExpensePaymentsRow, error)
	ListRecurringExpenseSplits(ctx context.Context, recurringExpenseID pgtype.UUID) ([]ListRecurringExpenseSplitsRow, error)
	ListRecurringExpensesByGroup(ctx context.Context, groupID pgtype.UUID) ([]RecurringExpense, error)
	ListSettlementsByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListSettlementsByGroupRow, error)
	ListSettlementsByUser(ctx context.Context, payerID pgtype.UUID) ([]ListSettlementsByUserRow, error)
	SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]Expense, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateExpenseComment(ctx context.Context, arg UpdateExpenseCommentParams) (ExpenseComment, error)
	UpdateExpenseSplit(ctx context.Context, arg UpdateExpenseSplitParams) (ExpenseSplit, error)
	UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error)
	UpdateGroupCategory(ctx context.Context, arg UpdateGroupCategoryParams) (ExpenseCategory, error)
	UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) (GroupMember, error)
	UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (GroupInvitation, error)
	UpdateNextOccurrenceDate(ctx context.Context, arg UpdateNextOccurrenceDateParams) (RecurringExpense, error)
	UpdatePendingPaymentUserID(ctx context.Context, arg UpdatePendingPaymentUserIDParams) error
	UpdatePendingSplitUserID(ctx context.Context, arg UpdatePendingSplitUserIDParams) error
	UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error)
	UpdateRecurringExpenseActiveStatus(ctx context.Context, arg UpdateRecurringExpenseActiveStatusParams) (RecurringExpense, error)
	UpdateSessionLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateSettlement(ctx context.Context, arg UpdateSettlementParams) (Settlement, error)
	UpdateSettlementStatus(ctx context.Context, arg UpdateSettlementStatusParams) (Settlement, error)
}

var _ Querier = (*Queries)(nil)
