// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: theme_presets.sql

package sqlc

import (
	"context"
)

const getThemePresetBySlug = `-- name: GetThemePresetBySlug :one
SELECT id, slug, label, family, is_active, created_at, updated_at
FROM theme_presets
WHERE slug = $1
`

func (q *Queries) GetThemePresetBySlug(ctx context.Context, slug string) (ThemePreset, error) {
	row := q.db.QueryRow(ctx, getThemePresetBySlug, slug)
	var i ThemePreset
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.Family,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listThemePresets = `-- name: ListThemePresets :many
SELECT id, slug, label, family, is_active, created_at, updated_at
FROM theme_presets
WHERE is_active = TRUE
ORDER BY slug
`

func (q *Queries) ListThemePresets(ctx context.Context) ([]ThemePreset, error) {
	rows, err := q.db.Query(ctx, listThemePresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemePreset{}
	for rows.Next() {
		var i ThemePreset
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.Family,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
