// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_themes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserTheme = `-- name: CreateUserTheme :one
INSERT INTO user_themes (
    user_id,
    name,
    base_preset_slug,
    font_family_key,
    light_tokens,
    dark_tokens
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, base_preset_slug, font_family_key, light_tokens, dark_tokens, created_at, updated_at, deleted_at
`

type CreateUserThemeParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Name           string      `json:"name"`
	BasePresetSlug string      `json:"base_preset_slug"`
	FontFamilyKey  string      `json:"font_family_key"`
	LightTokens    []byte      `json:"light_tokens"`
	DarkTokens     []byte      `json:"dark_tokens"`
}

func (q *Queries) CreateUserTheme(ctx context.Context, arg CreateUserThemeParams) (UserTheme, error) {
	row := q.db.QueryRow(ctx, createUserTheme,
		arg.UserID,
		arg.Name,
		arg.BasePresetSlug,
		arg.FontFamilyKey,
		arg.LightTokens,
		arg.DarkTokens,
	)
	var i UserTheme
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BasePresetSlug,
		&i.FontFamilyKey,
		&i.LightTokens,
		&i.DarkTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUserTheme = `-- name: DeleteUserTheme :exec
UPDATE user_themes
SET
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUserTheme(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTheme, id)
	return err
}

const getUserThemeByID = `-- name: GetUserThemeByID :one
SELECT id, user_id, name, base_preset_slug, font_family_key, light_tokens, dark_tokens, created_at, updated_at, deleted_at
FROM user_themes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserThemeByID(ctx context.Context, id pgtype.UUID) (UserTheme, error) {
	row := q.db.QueryRow(ctx, getUserThemeByID, id)
	var i UserTheme
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BasePresetSlug,
		&i.FontFamilyKey,
		&i.LightTokens,
		&i.DarkTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserThemes = `-- name: ListUserThemes :many
SELECT id, user_id, name, base_preset_slug, font_family_key, light_tokens, dark_tokens, created_at, updated_at, deleted_at
FROM user_themes
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListUserThemes(ctx context.Context, userID pgtype.UUID) ([]UserTheme, error) {
	rows, err := q.db.Query(ctx, listUserThemes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTheme{}
	for rows.Next() {
		var i UserTheme
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BasePresetSlug,
			&i.FontFamilyKey,
			&i.LightTokens,
			&i.DarkTokens,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserTheme = `-- name: UpdateUserTheme :one
UPDATE user_themes
SET
    name = $2,
    base_preset_slug = $3,
    font_family_key = $4,
    light_tokens = $5,
    dark_tokens = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, base_preset_slug, font_family_key, light_tokens, dark_tokens, created_at, updated_at, deleted_at
`

type UpdateUserThemeParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	BasePresetSlug string      `json:"base_preset_slug"`
	FontFamilyKey  string      `json:"font_family_key"`
	LightTokens    []byte      `json:"light_tokens"`
	DarkTokens     []byte      `json:"dark_tokens"`
}

func (q *Queries) UpdateUserTheme(ctx context.Context, arg UpdateUserThemeParams) (UserTheme, error) {
	row := q.db.QueryRow(ctx, updateUserTheme,
		arg.ID,
		arg.Name,
		arg.BasePresetSlug,
		arg.FontFamilyKey,
		arg.LightTokens,
		arg.DarkTokens,
	)
	var i UserTheme
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BasePresetSlug,
		&i.FontFamilyKey,
		&i.LightTokens,
		&i.DarkTokens,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
