// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_theme_preferences.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserThemePreferences = `-- name: GetUserThemePreferences :one
SELECT user_id, active_type, active_preset_slug, active_user_theme_id, mode, created_at, updated_at
FROM user_theme_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserThemePreferences(ctx context.Context, userID pgtype.UUID) (UserThemePreference, error) {
	row := q.db.QueryRow(ctx, getUserThemePreferences, userID)
	var i UserThemePreference
	err := row.Scan(
		&i.UserID,
		&i.ActiveType,
		&i.ActivePresetSlug,
		&i.ActiveUserThemeID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserThemePreferences = `-- name: UpsertUserThemePreferences :one
INSERT INTO user_theme_preferences (
    user_id,
    active_type,
    active_preset_slug,
    active_user_theme_id,
    mode
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
DO UPDATE SET
    active_type = EXCLUDED.active_type,
    active_preset_slug = EXCLUDED.active_preset_slug,
    active_user_theme_id = EXCLUDED.active_user_theme_id,
    mode = EXCLUDED.mode,
    updated_at = CURRENT_TIMESTAMP
RETURNING user_id, active_type, active_preset_slug, active_user_theme_id, mode, created_at, updated_at
`

type UpsertUserThemePreferencesParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	ActiveType        string      `json:"active_type"`
	ActivePresetSlug  pgtype.Text `json:"active_preset_slug"`
	ActiveUserThemeID pgtype.UUID `json:"active_user_theme_id"`
	Mode              string      `json:"mode"`
}

func (q *Queries) UpsertUserThemePreferences(ctx context.Context, arg UpsertUserThemePreferencesParams) (UserThemePreference, error) {
	row := q.db.QueryRow(ctx, upsertUserThemePreferences,
		arg.UserID,
		arg.ActiveType,
		arg.ActivePresetSlug,
		arg.ActiveUserThemeID,
		arg.Mode,
	)
	var i UserThemePreference
	err := row.Scan(
		&i.UserID,
		&i.ActiveType,
		&i.ActivePresetSlug,
		&i.ActiveUserThemeID,
		&i.Mode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
